### ISSUE TITLE
collectd.conf for Lustre 2.12

### ISSUE THREAD

**Issue by martinvelez** [DDNStorage/LustrePerfMon#1]
How can I generate or get a collectd.conf file for Lustre 2.12?

**Comment by LiXi-storage** [comment]
You can find the XML file from the xml RPM (xml_definition-xxx.noarch.rpm) generated from the project https://github.com/DDNStorage/monsystem_package/

And the XML file generated from the m4 file here:

https://github.com/DDNStorage/monsystem_package/tree/master/xml_definition

**Comment by ldd91** [comment]
Hi i am still confused  about how to support Lustre 2.12
