### ISSUE TITLE
Failed to check measurement

### ISSUE THREAD

**Issue by ldd91** [DDNStorage/LustrePerfMon#10]
I run esmon_install to setup LustrePerfMon in my lustre clustre,but failed white the debug log shows:
[ERROR][utils.py:464] timeout when waiting condition
[ERROR][esmon_install_nodeps.py:2110] failed to check measurement [memory.buffered.memory]
[ERROR][esmon_install_nodeps.py:2504] Influxdb doesn't have expected datapoints from host

**Comment by LiXi-storage** [comment]
Hi, this problem is usually because firewall is blocking the communications. Would you please check whether firewall is disabled or properly configured?

**Comment by ldd91** [comment]
I run systemctl status firewalld in all nodes,all of them are inactive

**Comment by ldd91** [comment]
In the /etc/esmon_install.conf i set auto_open_ports_on_firewall: true

**Comment by ldd91** [comment]
Hi @LiXi-storage  thank you ,i  start firewalld on install node and set auto_open_ports_on_firewall: true  and it works

**Comment by ldd91** [comment]
I have finished install LustrePerfMon,and in the grafana web i can see the information about server however the information of lustre is none

**Comment by ldd91** [comment]
My lustre version is 2.12.0.The debug info shows:
can't deterimine Lustre version according to RPM names pn host,possible version are [es2 es3 es4 2.7 2.12],using default [es3]

**Comment by LiXi-storage** [comment]
Please change the "lustre_default_version: es3" configuration to "lustre_default_version: 2.12" in /etc/esmon_install.conf, and the 2.12 XML file will be used under the current situation that Lustre version can't be determined through checking the RPM naming.

**Comment by LiXi-storage** [comment]
@ldd91 Would you please create another ticket about the issue of "can't deterimine Lustre version according to RPM names pn host,possible version are [es2 es3 es4 2.7 2.12],using default [es3]". This shouldn't happen and should be fixed.

It would be helpful if you can provide the names of your Lustre RPMs.

**Comment by ldd91** [comment]
I set lustre_default_version: 2.12 in /etc/esmon_install.conf,but is runs error,the log shows:
[ERROR] [esmon_install_nodeps.py:2252]unsupported Lustre version [2.12],please correct file [/etc/esmon_install.conf]
Okay i will create new issue about "can't deterimine Lustre version according to RPM names on host,possible version are [es2 es3 es4 2.7 2.12],using default [es3]"

**Comment by LiXi-storage** [comment]
The problem of "[ERROR] [esmon_install_nodeps.py:2252]unsupported Lustre version [2.12],please correct file [/etc/esmon_install.conf]" should have been fixed by https://github.com/DDNStorage/LustrePerfMon/commit/ac122dee29e483925f5d736ed806fe085bd3df4a.

The problem of "can't deterimine Lustre version according to RPM names pn host,possible version are [es2 es3 es4 2.7 2.12],using default [es3]" will be tracked in https://github.com/DDNStorage/LustrePerfMon/issues/11

I am closing this ticket.
