### ISSUE TITLE
can't deterimine Lustre version according to RPM names on host,possible version are [es2 es3 es4 2.7 2.12],using default [es3]

### ISSUE THREAD

**Issue by ldd91** [DDNStorage/LustrePerfMon#11]
My lustre version is 2.12.0.The debug info shows:
can't deterimine Lustre version according to RPM names 0n host [10.10.18.2],possible version are [es2 es3 es4 2.7 2.12],using default [es3]
10.10.18.2 is my MDS  node,and i exec "rpm -qa |grep lustre" in this node it shows:
lustre-2.12.0-957.el7.x86_64
kernel-3.10.0-957.el7_lustre.x86_64
kmod-lustre-2.12.0-1.el7.x86_64
kmod-lustre-osd-ldiskfs-2.12.0-1.el7.x86_64
lustre-iokit-2.12.0-1.el7.x86_64
kernel-devel-3.10.0-957.el7_lustre.x86_64
kernel-devel-3.10.0-957.10.1.el7_lustre.x86_64
lustre-osd-ldiskfs-mount-2.12.0-1.el7.x86_64
kernel-3.10.0-862.2.3.el7_lustre.x86_64

**Comment by LiXi-storage** [comment]
Fixing it now.

**Comment by ldd91** [comment]
I wonder if I need to rebuild iso

**Comment by ldd91** [comment]
Hi @ @LiXi-storage Our Lustre version in production environment is the lastst lustre-2.12.2-1.el7.x86_64 and we use InfiniBand,will you support this version?

**Comment by LiXi-storage** [comment]
This problem should have been fixed by https://github.com/DDNStorage/LustrePerfMon/commit/e06d677c9258f85a651edbb2e42a48dc0f87aaba.

@ldd91 Would you please rebuild the ISO and reinstall? The installation process should be able to detect the version 2.12 automatically and use XML for Lustre-2.12.

**Comment by ldd91** [comment]
Thank you @LiXi-storage I have rebuilded the ISO and reinstall,and the installation process was able to detect the version 2.12 automatically

**Comment by ldd91** [comment]
This issue can be closed

**Comment by LiXi-storage** [comment]
Thanks!
