### ISSUE TITLE
In grafana the lustre MDT  panel has not data

### ISSUE THREAD

**Issue by ldd91** [DDNStorage/LustrePerfMon#12]
Hi @LiXi-storage I run esmon_install successfully(Lustre version is 2.12.0),when i enter the grafana UI,the Lustre MDT panel has not data,the Filesystem Name: lustre MDT Index: None,I don'n know why,however the Lustre OST panel has data.I exec "systemctl status collected" every shows well

**Comment by LiXi-storage** [comment]
@ldd91 I fixed a problem of 2.12 XML file recently: https://github.com/DDNStorage/LustrePerfMon/commit/01ad647c0423a3ee08a076da9afed2bd652f67b2

Without that patch, the MDT index won't be able to parsed properly. Would you please check whether that helps?

**Comment by ldd91** [comment]
Thank you I will rebuild ISO and have a try

**Comment by ldd91** [comment]
Hi @LiXi-storage I have tried and  the MDT index is still None,I saw the patch is lustre 2.10?

**Comment by LiXi-storage** [comment]
Hi @ldd91 , I tried to reproduce the problem, but everything seems fine. Would you please double check that the XML file on MDS has been updated? The following command should print NOTHING:

`# cat /etc/lustre-2.12.xml | grep lod`

**Comment by ldd91** [comment]
[root@k8sv2master xml_definition]# cat /etc/lustre-2.12.xml | grep lod
                                <path>lod</path>

**Comment by LiXi-storage** [comment]
That means the XML is not updated. Is the ISO build updated correctly?

**Comment by ldd91** [comment]
I run git pull and ./esmon_build

**Comment by ldd91** [comment]
I will take a try

**Comment by ldd91** [comment]
@LiXi-storage sorry I make a mistake,I didnt exec cat  /etc/lustre-2.12.xml |grep lod in MDS node just now,when  I rexec "cat  /etc/lustre-2.12.xml |grep lod" in MDS node,and it print NOTHING

**Comment by ldd91** [comment]
Hi @LiXi-storage this issue can be close,it was my fault,I found that my MDS server is not running,when i remount lustre it works,and the MDT panel has data,thank you very much

**Comment by LiXi-storage** [comment]
Thanks @ldd91
