### ISSUE TITLE
Failed to disabled SELinux on host

### ISSUE THREAD

**Issue by ldd91** [DDNStorage/LustrePerfMon#13]
I run esmon_install and it occurs an error,the logs shows:
[ssh_host.py:1564] failed to run command [sed -i 's/SELinux=.*/SELinux=disabled/' /etc/selinux/config] on host 10.10.11.200
[ERROR][esmon_install_nodeps.py:2203] failed to disabled SELinux on host [10.10.11.200]
However i can exec ssh -a -x -l root -o StrictHostKeychecking=no -o BatchMode=yes -i /root/.ssh/id_rsa 10.10.11.200 "sed -i 's/SELinux=.*/SELinux=disabled/' /etc/selinux/config'"

**Comment by LiXi-storage** [comment]
Hello, The following log isn't complete. Would you please paste the whole log?

[ssh_host.py:1564] failed to run command [sed -i 's/SELinux=./SELinux=disabled/' /etc/selinux/config] on host 10.10.11.200

**Comment by ldd91** [comment]
[ssh_host.py:1564] failed to run command [sed -i 's/SELinux=./SELinux=disabled/' /etc/selinux/config] on host [10.10.11.220],ret=[0], stdout = [],stderr = [Warning: Permanently added '10.10.11.220' (ECDSA) to the list of knows hosts]
[ERROR][esmon_install_nodeps.py:2203] failed to disabled SELinux on host [10.10.11.200]

**Comment by LiXi-storage** [comment]
Hi @ldd91 , a patch is under test and will be pushed into the repository as soon as the regression test is passed. The test will take an hour or so.

**Comment by LiXi-storage** [comment]
The problem should have been fixed by https://github.com/DDNStorage/LustrePerfMon/commit/56182292fa945787b4487f32d37add160d39c44a

**Comment by ldd91** [comment]
Thank you @LiXi-storage I will have a try

**Comment by ldd91** [comment]
[ERROR][ssh_host.py:1547] failed to run command [getenforce] on host [10.10.11.200].ret = [0],stdout = [Disabled], stderr =  [Warning: Permanently added '10.10.11.220' (ECDSA) to the list of knows hosts]

**Comment by LiXi-storage** [comment]
Another patch is under test.

**Comment by ldd91** [comment]
Thank you @LiXi-storage  I found that my node has not known_hosts and I create a known_hosts and finally esmon_install succeed.
