### ISSUE TITLE
No data in Write Thruoghput per client panel

### ISSUE THREAD

**Issue by ldd91** [DDNStorage/LustrePerfMon#21]
I install the LustrePerfMon,and it works,but the Write Thruoghput per client panel show no data.I wonder if something must be installed in client node ?

**Comment by ldd91** [comment]
![客户端](https://user-images.githubusercontent.com/29392150/79594668-0addf680-8110-11ea-9be3-970072efee2b.png)

**Comment by LiXi-storage** [comment]
@ldd91 

To enable that panel, need to enable the following option when running esmon_install. And please note that enabling this option would cause high pressure to the monitoring system if there are huge number of clients:

lustre_exp_ost — Define whether to enable (true) or disable (false) metrics collection of export information of Lustre OST. To avoid a flood of metrics, this parameter is usually disabled in Lustre file systems with a large number of clients. Default value: false.

**Comment by ldd91** [comment]
Tks a lot,but how many clients is huge ? we now have about 50 clients in lustre.At the same time,will it cause the pressure of Lustre?

**Comment by LiXi-storage** [comment]
>  we now have about 50 clients in lustre.At the same time,will it cause the pressure of Lustre?

We saw high latency of LustrePerfMon when there are hundreds of Lustre clients. Given that Lustre could support thoudsands of clients, 50 clients is not a lot. And with reasonable hardware, it is very likely that LustrePerfMon can support that many clients. But that would require more tests and also depends on collect interval and other configurations.

**Comment by ldd91** [comment]
Will it add the pressure of the server,like OSS server?

**Comment by LiXi-storage** [comment]
Yes, it will. But the pressure won't be huge. It is more likely the bottleneck would be the InfluxDB on the monitoring server.

**Comment by ldd91** [comment]
Ok,thank you,we will have a test.
